#:import dp kivy.metrics.dp
#:import FitImage kivymd.uix.fitimage.FitImage
#:import MDSeparator ui_helpers.MDSeparator
#:import MDTopAppBar kivymd.uix.toolbar.MDTopAppBar
#:import MDIconButton kivymd.uix.button.MDIconButton


<MenuScreen>:
    name: "menu"

    MDBoxLayout:
        orientation: "vertical"
        padding: dp(20)
        spacing: dp(20)
  
        MDBoxLayout:
            orientation: "vertical"
            padding: dp(20)
            spacing: dp(15)
            size_hint_y: None
            height: dp(260)   # <-- creates space for logo + title + fact
            
            FitImage:
                source: "data/icon_1024.png"
                size_hint: None, None
                size: dp(120), dp(120)
                pos_hint: {"center_x": 0.5}

            MDLabel:
                id: title_label
                text: "Domino Scorebook"
                font_style: "H4"
                halign: "center"
                size_hint_y: None
                height: self.texture_size[1]

            MDLabel:
                id: fact_label
                text: root.get_fact()
                halign: "center"
                theme_text_color: "Secondary"
                text_size: self.width, None
                size_hint_y: None
                height: self.texture_size[1]
    
        MDRaisedButton:
            id: start_btn
            text: "Start Game"
            size_hint_y: None
            height: dp(48)
           #on_release: app.root.current = "select"
                
        MDRaisedButton:
            id: create_btn
            text: "Create Player"
            size_hint_y: None
            height: dp(48)
            #on_release: app.root.current = "create"
        
        MDRaisedButton:
            id: stats_btn
            text: "Player Stats"
            size_hint_y: None
            height: dp(48)
            #on_release: app.root.current = "stats"
        
        MDRaisedButton:
            id: history_btn
            text: "Game History"
            size_hint_y: None
            height: dp(48)
            #on_release: app.root.current = "history"
                
        Widget:
                
        MDSeparator:
        
        MDBoxLayout:
            size_hint_y: None
            height: dp(48)
            spacing: dp(20)
            pos_hint: {"center_x": 0.5}
            size_hint_x: None
            width: dp(260)  # controls how far apart they are
                    
            MDRaisedButton:
                text: "Options"
                size_hint_x: 1
                #on_release: app.root.current = "options"
            
            MDRaisedButton:
                text: "Exit"
                size_hint_x: 1
                on_release: app.stop()
